name: structurizr

services:
  lite:
    image: structurizr/lite:3234
    ports:
      - 8080:8080
    volumes:
      - ./dsl/:/usr/local/structurizr/
  on-premises:
    image: structurizr/onpremises:3263
    ports:
      - 8088:8080
    volumes:
      - ./storage:/usr/local/structurizr
